export const ROUTES = [
  {
    id: "workspace",
    path: "/",
    title: "Workspace",
    prototype: "home.html",
    surface: "workspace",
    auth: "user",
    summary: "Authenticated workspace dashboard with active and archived projects.",
  },
  {
    id: "new-project",
    path: "/new-project",
    title: "New Project",
    prototype: "new-project.html",
    surface: "workspace",
    auth: "user",
    summary: "Create a project and define its initial context.",
  },
  {
    id: "project",
    path: "/project/:projectId",
    title: "Project",
    prototype: "project.html",
    surface: "workspace",
    auth: "project",
    summary: "Project hub for graphs, members, and settings.",
  },
  {
    id: "import",
    path: "/project/:projectId/import",
    title: "Import",
    prototype: "import-wizard.html",
    surface: "workspace",
    auth: "project",
    summary: "Upload and validate graph JSON before creating a graph.",
  },
  {
    id: "canvas",
    path: "/project/:projectId/graph/:graphId",
    title: "Canvas",
    prototype: "canvas.html",
    surface: "canvas",
    auth: "project",
    summary: "Main graph viewer with views, lenses, inspector, replay, and export.",
  },
  {
    id: "profile",
    path: "/profile",
    title: "Profile",
    prototype: "profile.html",
    surface: "workspace",
    auth: "user",
    summary: "User account settings and profile details.",
  },
  {
    id: "sign-in",
    path: "/sign-in",
    title: "Sign In",
    prototype: "sign-in.html",
    surface: "auth",
    auth: "public-auth",
    summary: "Email and password sign-in.",
  },
  {
    id: "forgot",
    path: "/forgot",
    title: "Forgot Password",
    prototype: "forgot-password.html",
    surface: "auth",
    auth: "public-auth",
    summary: "Request a password reset link.",
  },
  {
    id: "reset",
    path: "/reset/:token",
    title: "Reset Password",
    prototype: "reset-password.html",
    surface: "auth",
    auth: "public-auth",
    summary: "Set a new password from a reset token.",
  },
  {
    id: "verify",
    path: "/verify/:token",
    title: "Verify Email",
    prototype: "verify-email.html",
    surface: "auth",
    auth: "public-auth",
    summary: "Confirm a new email address.",
  },
  {
    id: "invite",
    path: "/invite/:token",
    title: "Accept Invite",
    prototype: "accept-invite.html",
    surface: "auth",
    auth: "public-auth",
    summary: "Accept a workspace or project invitation.",
  },
  {
    id: "signed-out",
    path: "/signed-out",
    title: "Signed Out",
    prototype: "signed-out.html",
    surface: "auth",
    auth: "public",
    summary: "Confirmation after explicit sign-out.",
  },
  {
    id: "operator-sign-in",
    path: "/operator/sign-in",
    title: "Operator Sign In",
    prototype: "operator-sign-in.html",
    surface: "operator",
    auth: "operator-public",
    summary: "Separate operator authentication surface.",
  },
  {
    id: "operator-dashboard",
    path: "/operator/",
    title: "Operator Dashboard",
    prototype: "operator-dashboard.html",
    surface: "operator",
    auth: "operator",
    summary: "Operator overview metrics and system status.",
  },
  {
    id: "operator-users",
    path: "/operator/users",
    title: "Operator Users",
    prototype: "operator-users.html",
    surface: "operator",
    auth: "operator",
    summary: "User administration, filtering, and suspension controls.",
  },
  {
    id: "operator-invitations",
    path: "/operator/invitations",
    title: "Operator Invitations",
    prototype: "operator-invitations.html",
    surface: "operator",
    auth: "operator",
    summary: "Outstanding invitation administration.",
  },
  {
    id: "terms",
    path: "/terms",
    title: "Terms",
    prototype: "terms.html",
    surface: "auth",
    auth: "public",
    summary: "Public legal terms page.",
  },
  {
    id: "privacy",
    path: "/privacy",
    title: "Privacy",
    prototype: "privacy.html",
    surface: "auth",
    auth: "public",
    summary: "Public privacy page.",
  },
  {
    id: "not-found",
    path: "/404",
    title: "Not Found",
    prototype: "404.html",
    surface: "auth",
    auth: "public",
    summary: "Unknown route fallback.",
  },
  {
    id: "server-error",
    path: "/500",
    title: "Server Error",
    prototype: "500.html",
    surface: "auth",
    auth: "public",
    summary: "Unhandled app/server error page.",
  },
];
